// Copy for the "How it works" screen.
export const GUIDE = [
  {
    t: "Workspace",
    items: [
      { l: "Header & status strip", d: "56px bar with the ARGUS wordmark and one live dot per service. A dot pulses only while that service has an active anomaly — healthy and idle dots stay still. Click a dot to pan the graph to that service." },
      { l: "Service graph", d: "Every real service in the dependency graph, parsed from the indexed codebase and rendered on load before you ask anything — nothing is generated by a query. Only position is draggable; identity and edges come straight from the dependency graph. A node lights --brand as the trace reaches it, holds --critical if it's the confirmed root cause, and shows a dashed border with a \"needs review\" tag when the agent isn't confident." },
      { l: "Log stream", d: "The raw evidence, refreshed every few seconds straight from the log file. Each line has a severity dot; lines cited by the current report get a brand tint and a \"cited\" tag, right-aligned." },
      { l: "Chat", d: "Ask in plain language. Answers render as separate Root Cause / Evidence / Code / Fix cards, never one paragraph, staggered in as each resolves. A pulsing dot plus a rotating label (\"Analyzing logs…\", \"Tracing dependencies…\") shows the agent working, and a failed request says so instead of hanging." },
      { l: "Node detail panel", d: "Click any node to open it. Shows the relevant source code and recent logs for that one service, plus a one-line bridge explaining why they belong together. Click a cited log line to highlight the exact code line it explains, or click the code line to highlight the log back." },
    ],
  },
  {
    t: "Incident Report",
    items: [
      { l: "Status header", d: "Red \"INCIDENT — service name\" the moment a cause is confirmed; green \"No active incidents\" at idle." },
      { l: "Plain-language summary", d: "One sentence, no jargon — what happened, stated as fact." },
      { l: "Timeline", d: "Dots for first anomaly, escalation and diagnosis, colored with the same severity convention as the log stream." },
      { l: "Stat grid", d: "Every number is clickable and jumps straight to the log line that produced it — no number ships without a working source link." },
      { l: "Root cause & confidence", d: "The service name links back to the graph. A confidence tag reads \"High\" or \"Needs review\" and is always visible — this is the product's core trust signal, never hidden." },
      { l: "Evidence", d: "Citation chips, each clickable through to its source log line." },
      { l: "Relevant code & recommended fix", d: "Two separate blocks on purpose: the code the cause lives in, then a diff-styled fix — \"here's where it lives\" before \"here's what to change.\"" },
      { l: "Honest failure state", d: "If nothing clears the confidence bar, the header turns brand — not red — and says so directly: what was checked and what was ruled out, instead of a fabricated best guess." },
      { l: "Postmortem export", d: "One click formats the report already on screen into a markdown document and copies it — pure templating of existing data, no extra reasoning call." },
    ],
  },
  {
    t: "Blast Radius",
    items: [
      { l: "What it answers", d: "Which other services are affected by the root cause — a different question from which ones the agent walked through to find it." },
      { l: "How it's built", d: "Computed by walking the same dependency graph the Workspace already shows, outward from the root cause. No new data source." },
      { l: "On the graph", d: "Affected nodes get a small brand-tinted corner marker, distinct from the trace-path glow, so the two states can overlap without reading as the same thing." },
    ],
  },
];
